DROP TABLE IF EXISTS CUSTOMER_SERVICE;
CREATE TABLE CUSTOMER_SERVICE
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME  VARCHAR(50) NOT NULL,
    AGE        INT,
    PHONE      VARCHAR(20)
)
